default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", ENV.fetch("DB_HOST", "localhost")) %>
  port: <%= ENV.fetch("POSTGRES_PORT", ENV.fetch("DB_PORT", 5432)) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

development:
  <<: *default
  database: musik_development

test:
  <<: *default
  database: musik_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", ENV.fetch("DB_NAME", "musik_production")) %>
