[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:icecast]
command=icecast2 -c /etc/icecast.xml
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:tokyo]
command=/usr/local/bin/start_ffmpeg.sh tokyo.opus tokyo_lofi.mp3
autorestart=true
priority=20
startretries=1000000
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:focus]
command=/usr/local/bin/start_ffmpeg.sh focus.opus deep_focus.mp3
autorestart=true
priority=20
startretries=1000000
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:anime]
command=/usr/local/bin/start_ffmpeg.sh anime.opus anime_lofi.mp3
autorestart=true
priority=20
startretries=1000000
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:anime2]
command=/usr/local/bin/start_ffmpeg.sh anime2.opus anime_lofi_2.mp3
autorestart=true
priority=20
startretries=1000000
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:akita]
command=/usr/local/bin/start_ffmpeg.sh akita.opus akita.mp3
autorestart=true
priority=20
startretries=1000000
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
