services:
  bot-lofi:
    build: .
    image: musik-bot-lofi:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      # backup ta em /mnt/ssd/@docker/musik/secrets/bot-lofi.env
      - .env:/app/.env
      - ./data:/app/data
